### ISSUE TITLE
[bug] swapping from a smaller resolution emulator to a higher one, triggers indexoutofboundsexception on sharedtexture buffer

### ISSUE THREAD

**Issue by mutmedia** [plunderludics/BizHawk#1]
to reproduce, load an n64 game and load a sample for a psx game.

mainform line 860

**Comment by iatenothingbutriceforthreedays** [comment]
I think i fixed this at some point a couple of months ago, should double check

**Comment by iatenothingbutriceforthreedays** [comment]
One of the tests in the test suite does this (nes -> n64), seems to be fixed
